fix indention steps

diff --git a/.github/workflows/require_changelog.yml b/.github/workflows/require_changelog.yml
--- a/.github/workflows/require_changelog.yml
+++ b/.github/workflows/require_changelog.yml
@@ -12,29 +12,29 @@ jobs:
     runs-on: ubuntu-latest
     env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
-      steps:
-        - name: continue only iff this is a feature or hotfix pr
-          if: startsWith(${{ github.head_ref }}, 'feature') == false && startsWith(${{ github.head_ref }}, 'hotfix') == false
-          run: |
-            echo "This check is required for merging into develop and master but takes in action only for pr's from feature or hotfix branches."
-            exit 0
-        - name: Get Changed Files
-          id: changed
-          uses: foodee/pr-includes-file-change@master
-          with:
-            paths: ^CHANGELOG.md
-        - name: current head branch name
-          run: echo ${{ github.head_ref }}
-        - name: Changelog has been updated
-          if: steps.changed.outputs.matched == 'true'
-          run: |
-            echo ${{ steps.changed.outputs.matched }}
-            echo "Changes in CHANGELOG.md have been found"
-            exit 0
-        - name: Changelog updates missing
-          if: steps.changed.outputs.matched != 'true'
-          run: |
-            echo ${{ steps.changed.outputs.matched }}
-            echo "Features and Hotfixes must contain a changelog entry."
-            echo "Add meaningful information into CHANGELOG.md about this PR."
-            exit 1
+    steps:
+      - name: continue only iff this is a feature or hotfix pr
+        if: startsWith(${{ github.head_ref }}, 'feature') == false && startsWith(${{ github.head_ref }}, 'hotfix') == false
+        run: |
+          echo "This check is required for merging into develop and master but takes in action only for pr's from feature or hotfix branches."
+          exit 0
+      - name: Get Changed Files
+        id: changed
+        uses: foodee/pr-includes-file-change@master
+        with:
+          paths: ^CHANGELOG.md
+      - name: current head branch name
+        run: echo ${{ github.head_ref }}
+      - name: Changelog has been updated
+        if: steps.changed.outputs.matched == 'true'
+        run: |
+          echo ${{ steps.changed.outputs.matched }}
+          echo "Changes in CHANGELOG.md have been found"
+          exit 0
+      - name: Changelog updates missing
+        if: steps.changed.outputs.matched != 'true'
+        run: |
+          echo ${{ steps.changed.outputs.matched }}
+          echo "Features and Hotfixes must contain a changelog entry."
+          echo "Add meaningful information into CHANGELOG.md about this PR."
+          exit 1
